-- MySQL Script generated by MySQL Workbench
-- 04/02/15 10:52:06
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`actor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`actor` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(255) NOT NULL,
  `lastname` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`store`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`store` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `address` VARCHAR(255) NOT NULL,
  `phone` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`employee` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(255) NOT NULL,
  `lastname` VARCHAR(255) NOT NULL,
  `dob` DATE NOT NULL,
  `address` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `phone` VARCHAR(255) NOT NULL,
  `store_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_employee_store1_idx` (`store_id` ASC),
  CONSTRAINT `fk_employee_store1`
    FOREIGN KEY (`store_id`)
    REFERENCES `mydb`.`store` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`genre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`genre` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`location`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`location` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `date` DATE NOT NULL,
  `expirationdate` DATE NOT NULL,
  `backdate` DATE NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`member`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`member` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(255) NOT NULL,
  `lastname` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `dob` DATE NOT NULL,
  `phone` VARCHAR(255) NOT NULL,
  `address` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`productor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`productor` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(255) NOT NULL,
  `lastname` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`realisator`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`realisator` (
  `id` INT NOT NULL,
  `firstname` VARCHAR(255) NOT NULL,
  `lastname` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`support`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`support` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `stockDvd` INT NULL,
  `stockCassette` INT NULL,
  `stockBlury` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`video`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`video` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NOT NULL,
  `illustration` VARCHAR(255) NOT NULL,
  `synopsis` TEXT NOT NULL,
  `publication_date` DATE NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`video_actor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`video_actor` (
  `actorid` INT(11) NOT NULL,
  `videoid` INT(11) NOT NULL,
  INDEX `fk_video_actor_actor1_idx` (`actorid` ASC),
  INDEX `fk_video_actor_video1_idx` (`videoid` ASC),
  CONSTRAINT `fk_video_actor_actor1`
    FOREIGN KEY (`actorid`)
    REFERENCES `mydb`.`actor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_video_actor_video1`
    FOREIGN KEY (`videoid`)
    REFERENCES `mydb`.`video` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`video_genre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`video_genre` (
  `videoid` INT(11) NOT NULL,
  `genreid` INT(11) NOT NULL,
  INDEX `fk_video_genre_video1_idx` (`videoid` ASC),
  INDEX `fk_video_genre_genre1_idx` (`genreid` ASC),
  CONSTRAINT `fk_video_genre_video1`
    FOREIGN KEY (`videoid`)
    REFERENCES `mydb`.`video` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_video_genre_genre1`
    FOREIGN KEY (`genreid`)
    REFERENCES `mydb`.`genre` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`video_rent`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`video_rent` (
  `videoid` INT(11) NOT NULL,
  `rentid` INT(11) NOT NULL,
  `memberid` INT(11) NOT NULL,
  `storeid` INT(11) NOT NULL,
  `support_id` INT(11) NOT NULL,
  INDEX `fk_video_location_video1_idx` (`videoid` ASC),
  INDEX `fk_video_location_location1_idx` (`rentid` ASC),
  INDEX `fk_video_location_member1_idx` (`memberid` ASC),
  INDEX `fk_video_location_store1_idx` (`storeid` ASC),
  INDEX `fk_video_location_support1_idx` (`support_id` ASC),
  CONSTRAINT `fk_video_location_video1`
    FOREIGN KEY (`videoid`)
    REFERENCES `mydb`.`video` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_video_location_location1`
    FOREIGN KEY (`rentid`)
    REFERENCES `mydb`.`location` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_video_location_member1`
    FOREIGN KEY (`memberid`)
    REFERENCES `mydb`.`member` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_video_location_store1`
    FOREIGN KEY (`storeid`)
    REFERENCES `mydb`.`store` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_video_location_support1`
    FOREIGN KEY (`support_id`)
    REFERENCES `mydb`.`support` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`video_productor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`video_productor` (
  `videoid` INT(11) NOT NULL,
  `productorid` INT(11) NOT NULL,
  INDEX `fk_video_productor_video1_idx` (`videoid` ASC),
  INDEX `fk_video_productor_productor1_idx` (`productorid` ASC),
  CONSTRAINT `fk_video_productor_video1`
    FOREIGN KEY (`videoid`)
    REFERENCES `mydb`.`video` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_video_productor_productor1`
    FOREIGN KEY (`productorid`)
    REFERENCES `mydb`.`productor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`video_realisator`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`video_realisator` (
  `videoid` INT(11) NOT NULL,
  `realisatorid` INT(11) NOT NULL,
  INDEX `fk_video_realisator_video1_idx` (`videoid` ASC),
  INDEX `fk_video_realisator_realisator1_idx` (`realisatorid` ASC),
  CONSTRAINT `fk_video_realisator_video1`
    FOREIGN KEY (`videoid`)
    REFERENCES `mydb`.`video` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_video_realisator_realisator1`
    FOREIGN KEY (`realisatorid`)
    REFERENCES `mydb`.`realisator` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`video_support`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`video_support` (
  `videoid` INT(11) NOT NULL,
  `supportid` INT(11) NOT NULL,
  `storeid` INT(11) NOT NULL,
  INDEX `fk_video_support_video_idx` (`videoid` ASC),
  INDEX `fk_video_support_support1_idx` (`supportid` ASC),
  INDEX `fk_video_support_store1_idx` (`storeid` ASC),
  CONSTRAINT `fk_video_support_video`
    FOREIGN KEY (`videoid`)
    REFERENCES `mydb`.`video` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_video_support_support1`
    FOREIGN KEY (`supportid`)
    REFERENCES `mydb`.`support` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_video_support_store1`
    FOREIGN KEY (`storeid`)
    REFERENCES `mydb`.`store` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
